// <auto-generated />
using System;
using Deadliner.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deadliner.API.Migrations
{
    [DbContext(typeof(DeadlinerContext))]
    partial class DeadlinerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deadliner.API.Models.EtapProizvodstva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdRoliOtvetstvennogo")
                        .HasColumnType("int");

                    b.Property<string>("Nazvanie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoryadkovyNomer")
                        .HasColumnType("int");

                    b.Property<int?>("RolOtvetstvennogoId")
                        .HasColumnType("int");

                    b.Property<string>("TipEtapa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolOtvetstvennogoId");

                    b.ToTable("EtapYProizvodstva");
                });

            modelBuilder.Entity("Deadliner.API.Models.EtapZakaza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtapId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FactData")
                        .HasColumnType("date");

                    b.Property<int>("IdEtapa")
                        .HasColumnType("int");

                    b.Property<int?>("IdSotrudnika")
                        .HasColumnType("int");

                    b.Property<int>("IdZakaza")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PlanData")
                        .HasColumnType("date");

                    b.Property<int?>("SotrudnikId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZakazId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EtapId");

                    b.HasIndex("SotrudnikId");

                    b.HasIndex("ZakazId");

                    b.ToTable("EtapyZakazov");
                });

            modelBuilder.Entity("Deadliner.API.Models.Izdelie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Harakteristiki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdZakaza")
                        .HasColumnType("int");

                    b.Property<int>("Kolichestvo")
                        .HasColumnType("int");

                    b.Property<string>("Naimenovanie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZakazId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZakazId");

                    b.ToTable("Izdeliya");
                });

            modelBuilder.Entity("Deadliner.API.Models.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresObekta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FioNazvanie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klienty");
                });

            modelBuilder.Entity("Deadliner.API.Models.PorogSrochnosti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cvet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DneyDo")
                        .HasColumnType("int");

                    b.Property<int>("DneyOt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PorogiSrochnosti");
                });

            modelBuilder.Entity("Deadliner.API.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazvanie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roli");
                });

            modelBuilder.Entity("Deadliner.API.Models.Sotrudnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRoli")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Sotrudniki");
                });

            modelBuilder.Entity("Deadliner.API.Models.Zakaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataPriema")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FactDataOtgruzki")
                        .HasColumnType("date");

                    b.Property<int>("IdKlienta")
                        .HasColumnType("int");

                    b.Property<int>("IdMenedzhera")
                        .HasColumnType("int");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("MenedzherId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PlanDataOtgruzki")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SummaPredoplaty")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.HasIndex("MenedzherId");

                    b.ToTable("Zakazy");
                });

            modelBuilder.Entity("Deadliner.API.Models.ZhurnalIzmenenii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataIzmenenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSotrudnika")
                        .HasColumnType("int");

                    b.Property<int>("IdZakaza")
                        .HasColumnType("int");

                    b.Property<string>("OpisanieIzmenenia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdSotrudnika");

                    b.HasIndex("IdZakaza");

                    b.ToTable("ZhurnalIzmenenii");
                });

            modelBuilder.Entity("Deadliner.API.Models.EtapProizvodstva", b =>
                {
                    b.HasOne("Deadliner.API.Models.Rol", "RolOtvetstvennogo")
                        .WithMany("EtapyProizvodstva")
                        .HasForeignKey("RolOtvetstvennogoId");

                    b.Navigation("RolOtvetstvennogo");
                });

            modelBuilder.Entity("Deadliner.API.Models.EtapZakaza", b =>
                {
                    b.HasOne("Deadliner.API.Models.EtapProizvodstva", "Etap")
                        .WithMany("EtapyZakazov")
                        .HasForeignKey("EtapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Deadliner.API.Models.Sotrudnik", "Sotrudnik")
                        .WithMany("EtapyZakazov")
                        .HasForeignKey("SotrudnikId");

                    b.HasOne("Deadliner.API.Models.Zakaz", "Zakaz")
                        .WithMany("EtapyZakaza")
                        .HasForeignKey("ZakazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etap");

                    b.Navigation("Sotrudnik");

                    b.Navigation("Zakaz");
                });

            modelBuilder.Entity("Deadliner.API.Models.Izdelie", b =>
                {
                    b.HasOne("Deadliner.API.Models.Zakaz", "Zakaz")
                        .WithMany("Izdeliya")
                        .HasForeignKey("ZakazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zakaz");
                });

            modelBuilder.Entity("Deadliner.API.Models.Sotrudnik", b =>
                {
                    b.HasOne("Deadliner.API.Models.Rol", "Rol")
                        .WithMany("Sotrudniki")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Deadliner.API.Models.Zakaz", b =>
                {
                    b.HasOne("Deadliner.API.Models.Klient", "Klient")
                        .WithMany("Zakazy")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Deadliner.API.Models.Sotrudnik", "Menedzher")
                        .WithMany("Zakazy")
                        .HasForeignKey("MenedzherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Menedzher");
                });

            modelBuilder.Entity("Deadliner.API.Models.ZhurnalIzmenenii", b =>
                {
                    b.HasOne("Deadliner.API.Models.Sotrudnik", "Sotrudnik")
                        .WithMany("ZhurnalIzmenenii")
                        .HasForeignKey("IdSotrudnika")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Deadliner.API.Models.Zakaz", "Zakaz")
                        .WithMany("ZhurnalIzmenenii")
                        .HasForeignKey("IdZakaza")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sotrudnik");

                    b.Navigation("Zakaz");
                });

            modelBuilder.Entity("Deadliner.API.Models.EtapProizvodstva", b =>
                {
                    b.Navigation("EtapyZakazov");
                });

            modelBuilder.Entity("Deadliner.API.Models.Klient", b =>
                {
                    b.Navigation("Zakazy");
                });

            modelBuilder.Entity("Deadliner.API.Models.Rol", b =>
                {
                    b.Navigation("EtapyProizvodstva");

                    b.Navigation("Sotrudniki");
                });

            modelBuilder.Entity("Deadliner.API.Models.Sotrudnik", b =>
                {
                    b.Navigation("EtapyZakazov");

                    b.Navigation("Zakazy");

                    b.Navigation("ZhurnalIzmenenii");
                });

            modelBuilder.Entity("Deadliner.API.Models.Zakaz", b =>
                {
                    b.Navigation("EtapyZakaza");

                    b.Navigation("Izdeliya");

                    b.Navigation("ZhurnalIzmenenii");
                });
#pragma warning restore 612, 618
        }
    }
}
